#!/usr/bin/env bash
# Render lua/ddlc/palette.lua from ddlc-palette's base16 schemes. The group tables next to it are
# the theme's own design and are written by hand — only the colours come from upstream
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
out="$here/lua/ddlc/palette.lua"

usage() {
  cat <<EOF
generate.sh — render the palette table out of the base16 schemes

  --light FILE   base16-ddlc-light.yaml   (or \$DDLC_BASE16_LIGHT)
  --dark FILE    base16-ddlc-dark.yaml    (or \$DDLC_BASE16_DARK)

Both come from ddlc-palette, and nix develop puts them in the environment already.
Without Nix, take them from the palette repository:

  curl -sSLO https://raw.githubusercontent.com/rokokol/ddlc-palette/master/dist/base16-ddlc-dark.yaml
EOF
}

declare -A scheme=(
  [light]="${DDLC_BASE16_LIGHT:-}"
  [dark]="${DDLC_BASE16_DARK:-}"
)

while [[ $# -gt 0 ]]; do
  case "$1" in
    --light)
      scheme[light]="${2:?file required}"
      shift 2
      ;;
    --dark)
      scheme[dark]="${2:?file required}"
      shift 2
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

slots() { sed -n 's/^  \(base[0-9A-F][0-9A-F]\): "\(#[0-9A-F]\{6\}\)".*/\1 \2/p' "$1"; }

for variant in light dark; do
  file="${scheme[$variant]}"
  [ -n "$file" ] || {
    echo "generate.sh: no $variant scheme — pass --$variant or set DDLC_BASE16_${variant^^}" >&2
    exit 1
  }
  # Sixteen slots or it is not a base16 scheme, and a half-read file would render a half-theme
  n=$(slots "$file" | wc -l)
  [ "$n" = 16 ] || {
    echo "generate.sh: $file has $n slots, want 16" >&2
    exit 1
  }
done

{
  echo "-- Generated by generate.sh from ddlc-palette's base16 schemes — do not edit"
  echo "return {"
  for variant in dark light; do
    echo "  $variant = {"
    slots "${scheme[$variant]}" | while read -r key hex; do echo "    $key = \"$hex\","; done
    echo "  },"
  done
  echo "}"
} >"$out"

echo "wrote $out"
