-- The groups vim and neovim define themselves. Everything else in this directory hangs off
-- these, so a plugin left without an integration still lands somewhere sane
return function(c, cfg)
  local comment = { fg = c.base03, italic = cfg.italic_comments }

  return {
    -- Editor
    Normal = { fg = c.base05, bg = c.base00 },
    NormalNC = { fg = c.base05, bg = c.base00 },
    NormalFloat = { fg = c.base05, bg = c.base01 },
    FloatBorder = { fg = c.base03, bg = c.base01 },
    FloatTitle = { fg = c.base0E, bg = c.base01 },
    Cursor = { fg = c.base00, bg = c.base05 },
    lCursor = { fg = c.base00, bg = c.base05 },
    TermCursor = { fg = c.base00, bg = c.base05 },
    CursorLine = { bg = c.base01 },
    CursorColumn = { bg = c.base01 },
    ColorColumn = { bg = c.base01 },
    LineNr = { fg = c.base04, bg = c.base00 },
    CursorLineNr = { fg = c.base06, bg = c.base01 },
    SignColumn = { fg = c.base04, bg = c.base00 },
    CursorLineSign = { link = "SignColumn" },
    FoldColumn = { fg = c.base0C, bg = c.base00 },
    Folded = { fg = c.base03, bg = c.base01 },
    NonText = { fg = c.base03 },
    EndOfBuffer = { fg = c.base03 },
    Whitespace = { fg = c.base03 },
    SpecialKey = { fg = c.base03 },
    Conceal = { fg = c.base0D },
    Directory = { fg = c.base0D },
    Title = { fg = c.base0D, bold = true },
    QuickFixLine = { bg = c.base01 },
    MatchParen = { bg = c.base03 },
    Visual = { bg = c.base02 },
    VisualNOS = { fg = c.base08 },

    -- Search
    Search = { fg = c.base01, bg = c.base0A },
    IncSearch = { fg = c.base01, bg = c.base09 },
    CurSearch = { fg = c.base01, bg = c.base09 },
    Substitute = { fg = c.base01, bg = c.base09 },

    -- Chrome
    StatusLine = { fg = c.base04, bg = c.base02 },
    StatusLineNC = { fg = c.base03, bg = c.base01 },
    WinBar = { fg = c.base05, bold = true },
    WinBarNC = { fg = c.base03 },
    VertSplit = { fg = c.base02 },
    WinSeparator = { fg = c.base02 },
    TabLine = { fg = c.base03, bg = c.base01 },
    TabLineFill = { fg = c.base03, bg = c.base01 },
    TabLineSel = { fg = c.base0B, bg = c.base01 },

    -- Completion menu
    Pmenu = { fg = c.base05, bg = c.base01 },
    PmenuSel = { fg = c.base01, bg = c.base05 },
    PmenuKind = { fg = c.base0A, bg = c.base01 },
    PmenuKindSel = { fg = c.base01, bg = c.base05 },
    PmenuExtra = { fg = c.base03, bg = c.base01 },
    PmenuExtraSel = { fg = c.base01, bg = c.base05 },
    PmenuMatch = { fg = c.base0A, bg = c.base01 },
    PmenuMatchSel = { fg = c.base01, bg = c.base05, bold = true },
    PmenuSbar = { bg = c.base02 },
    PmenuThumb = { bg = c.base07 },
    WildMenu = { fg = c.base01, bg = c.base05 },

    -- Messages
    ModeMsg = { fg = c.base0B },
    MoreMsg = { fg = c.base0B },
    MsgArea = { fg = c.base05 },
    MsgSeparator = { fg = c.base03, bg = c.base01 },
    Question = { fg = c.base0B },
    WarningMsg = { fg = c.base08 },
    ErrorMsg = { fg = c.base08 },
    Error = { fg = c.base00, bg = c.base08 },
    Todo = { fg = c.base0A, bg = c.base01 },

    -- Syntax, the pre-treesitter names. Still what a filetype without a parser gets
    Comment = comment,
    Constant = { fg = c.base09 },
    String = { fg = c.base0B },
    Character = { fg = c.base08 },
    Number = { fg = c.base09 },
    Boolean = { fg = c.base09 },
    Float = { fg = c.base09 },
    Identifier = { fg = c.base08 },
    Function = { fg = c.base0D },
    Statement = { fg = c.base0E },
    Conditional = { fg = c.base0E },
    Repeat = { fg = c.base0E },
    Label = { fg = c.base0A },
    Operator = { fg = c.base05 },
    Keyword = { fg = c.base0E },
    Exception = { fg = c.base08 },
    PreProc = { fg = c.base0A },
    Include = { fg = c.base0D },
    Define = { fg = c.base0E },
    Macro = { fg = c.base08 },
    PreCondit = { fg = c.base0A },
    Type = { fg = c.base0A },
    StorageClass = { fg = c.base0A },
    Structure = { fg = c.base0E },
    Typedef = { fg = c.base0A },
    Special = { fg = c.base0C },
    SpecialChar = { fg = c.base0F },
    Tag = { fg = c.base0A },
    Delimiter = { fg = c.base0F },
    Debug = { fg = c.base08 },
    Underlined = { fg = c.base08, underline = true },
    Ignore = { fg = c.base00 },

    -- Diffs, in both spellings: the four vim groups and the three neovim ones
    DiffAdd = { fg = c.base0B, bg = c.base01 },
    DiffChange = { fg = c.base03, bg = c.base01 },
    DiffDelete = { fg = c.base08, bg = c.base01 },
    DiffText = { fg = c.base0D, bg = c.base01 },
    Added = { fg = c.base0B },
    Changed = { fg = c.base0D },
    Removed = { fg = c.base08 },

    -- The undercurl carries the colour, so the word keeps the syntax it already had
    SpellBad = { sp = c.base08, undercurl = true },
    SpellCap = { sp = c.base0D, undercurl = true },
    SpellLocal = { sp = c.base0C, undercurl = true },
    SpellRare = { sp = c.base0E, undercurl = true },
  }
end
